### ISSUE TITLE
Regexp and new strings in Italian, French and Spanish

### ISSUE THREAD

**Issue by maxbambi** [al-caughey/Google-Meet-Attendance#10]
It seems that since you changed your code from `let pn=aa.innerText` to 
`let pn=aa.innerHTML.replace(/<[^>]*?>/ig,'\n').replace(/\n\n*/gm,'\n')`, erasing all tags is not enough to clean strings, but some other text remains in addition to names.
In particular I have found this word "Partecipa", that is the present tense of "partecipare" (to take part)

Note: I have made a temporary patch adding a `.replace("partecipa","")`

**Comment by al-caughey** [comment]
Does it also work if you make the changes to Line 39:   
-  it:{ presenting:"presentando", presentation:"presentazione", you:"tu", joined:"sta partecipando", more:"and \d* more"},
+ it:{ presenting:"presentando", presentation:"presentazione", you:"tu", joined:"(sta partecipando)|partecipa", more:"and \d* more"}, 
i.e., add both tenses to the joined string?

Can you also provide a translation for the `more` string?

Looking back, I think line 396 should wrap the strings in round brackets too
- let re_replace = new RegExp('\\b'+strings.you+'|'+strings.joined+'|'+strings.more+'\\b', "gi");]  - let + re_replace = new RegExp('\\b('+strings.you+'|'+strings.joined+'|'+strings.more+')\\b', "gi");]  //i.e., wrap the strings in round brackets

**Comment by al-caughey** [comment]
BTW  - the reason for changing from innerText to innerHTML and then stripping the tags is that innerText returns all of the text concatenated as a single string (hence the duplication of names)

With the innerHTML, as I strip the tags, I put the text on to individual lines and then can more easily manage things.
I wrestled with it can could not come up with a simpler way that that.  If you've got a better idea, I'm all ears

**Comment by maxbambi** [comment]
> Can you also provide a translation for the `more` string?
> 
Read my pull request!

**Comment by maxbambi** [comment]
My suggestion for strings (updated italian and french)
```
	const translations={
		en:{ presenting:"presenting", presentation:"presentation", you:"you", joined:"(has |)joined", more:"and \\d* more"},
		fr:{ presenting:"présentez", presentation:"présentation", you:"vous", joined:"(participe|à l'appel[.])", more:"et \\d* ont rejoint l'appel"},
		de:{ presenting:"präsentation", presentation:"blidschirm", you:"ich", joined:"nimmt teil", more:"and \\d* more"},
		nl:{ presenting:"presentatie", presentation:"presenteert", you:"jij", joined:"neemt( nu | )deel", more:"and \\d* more"},
		br:{ presenting:"apresentando", presentation:"apresentação", you:"you", joined:"joined", more:"and \\d* more"},
		es:{ presenting:"presenting", presentation:"presentación", you:"tú", joined:"se ha unido", more:"and \\d* more"},
		pt:{ presenting:"apresentando", presentation:"apresentação", you:"eu", joined:"aderiu( à chamada|)", more:"and \\d* more"},
		it:{ presenting:"presentando", presentation:"presentazione", you:"tu", joined:"(sta partecipando|partecipa)", more:"e altri \\d* stanno partecipando"},
	}
```
In my opinion, this version should work:
```
let re_replace = new RegExp('\\b'+strings.you+'\\b|\\b'+strings.joined+'\\b|\\b'+strings.more+'\\b', "gi");
``` 
but also this one seems to give same result:
```
let re_replace = new RegExp('\\b('+strings.you+'|'+strings.joined+'|'+strings.more+')\\b', "gi");
```

**Comment by maxbambi** [comment]
New update (spanish):

```
	const translations={
		en:{ presenting:"presenting", presentation:"presentation", you:"you", joined:"(has |)joined", more:"and \\d* more"},
		fr:{ presenting:"présentez", presentation:"présentation", you:"vous", joined:"(participe|à l'appel[.])", more:"et \\d* ont rejoint l'appel"},
		de:{ presenting:"präsentation", presentation:"blidschirm", you:"ich", joined:"nimmt teil", more:"and \\d* more"},
		nl:{ presenting:"presentatie", presentation:"presenteert", you:"jij", joined:"neemt( nu | )deel", more:"and \\d* more"},
		br:{ presenting:"apresentando", presentation:"apresentação", you:"you", joined:"joined", more:"and \\d* more"},
		es:{ presenting:"presenting", presentation:"presentación", you:"tú", joined:"se ha unido", more:"y \\d* personas más se han unido"},
		pt:{ presenting:"apresentando", presentation:"apresentação", you:"eu", joined:"aderiu( à chamada|)", more:"and \\d* more"},
		it:{ presenting:"presentando", presentation:"presentazione", you:"tu", joined:"(sta partecipando|partecipa)", more:"e altri \\d* stanno partecipando"},
	}
```
'you' string  in Spanish creates some problems because it ends with an accented vowel and
this clashes with '\b' in regular expressions. 
It seems working to use and '\n' instead of '\b' after pronoun 
```
let re_replace = new RegExp('\\b'+strings.you+'\n|\\b'+strings.joined+'\\b|\\b'+strings.more+'\\b', "gi");
```

**Comment by al-caughey** [comment]
Ok... rolled your changes in

It's just occurred to me that that in the more string, we don't care what comes after the number... right?
In most cases, all we really need is the `and \\d*.*` or `e altri \\d*.*`... etc.

**Comment by al-caughey** [comment]
closed...
