### ISSUE TITLE
0.4.3: problems in visualization and use

### ISSUE THREAD

**Issue by mauriva** [al-caughey/Google-Meet-Attendance#12]
After the last update of the extension, I have problems both in the window display and in the use.
When starting Meet, for a second I see the extension window correctly, but immediately after it looks like this:
![image](https://user-images.githubusercontent.com/39453887/80345422-5f4c4900-8869-11ea-9841-e2c4ac2cecb7.png)
If I click on the "folder" icon, appears a window to open a file. 
Uninstall and reinstall the extension doesn't help: I don't know if I must delete something manually for a clean uninstall...
I'm on Windows Pro 64 bit, Chrome ver. 81.0.4044.122 64 bit and Google Meet Attendance ver. 0.4.3.

**Comment by AlCaughey** [comment]
Weird... I've not seen that.  It is almost like things are not fully
refreshed.  What happens if you force a refresh ([ctrl]+[shift]+F5)?

**Comment by mauriva** [comment]
[ctrl]+[shift]+F5 do nothing.
If I make a refresh (F5) I see this for one second:
![immagine](https://user-images.githubusercontent.com/39453887/80391869-9e50bd80-88ae-11ea-8273-81272cbb2626.png)
After this the window appears as reported in the first post.

**Comment by AlCaughey** [comment]
what is saved in your localstorage keys?
Open Meet
right click anywhere on the page and choose Inspect and then change to the
`Application` tab (#1), then drill into `Storage` --> `Local Storage` --> `
https://meet.google.com` (#2) and then look at the keys and values (#3)
[image: image.png]

**Comment by mauriva** [comment]
Sorry, I didn't understand: what keys and values?

**Comment by mauriva** [comment]
In your previous post it seems you attached an image that I can't see.
Here is some screenshot:
![immagine](https://user-images.githubusercontent.com/39453887/80453227-21622a00-8928-11ea-9bd8-bdce0f43223b.png)
below:
![immagine](https://user-images.githubusercontent.com/39453887/80453314-48206080-8928-11ea-814c-6fcea30314f3.png)

**Comment by AlCaughey** [comment]
Is this still an issue for you? Your local storage values look good. I get the impression it's a result of cached css files.

The errors in the second screen shot are not related to the attendance extension

**Comment by mauriva** [comment]
Unfortunately nothing has changed and the extension still works as described in the first post.
I have no idea how to manually remove any css file that causes this malfunction.
Any suggestions?

**Comment by al-caughey** [comment]
Sorry - I missed your response.  Are you using Chrome on a Mac?

**Comment by al-caughey** [comment]
Are you using the Grid View extension too?

Guess what happened when I started my Meet this morning?  All of my buttons were gone... I think just like yours. 

I fixed the problem by disabling the Grid View extension and then reloaded my Meet... boom, the images came back.  I then re-enabled Grid View and they continue to work. 

I cannot make them go away again so I really don't know what actually caused the issue.

Right click on the Grid View extension icon in the browser toolbar, choose `Manage Extensions`, click the `On` button to disable it.  Then return to your Meet and reload the page... AFAIK, the images will reappear.  

Let me know if this helps you

**Comment by mauriva** [comment]
Hi!
Yes, I'm using the Grid View extension but I can not disable it because it's forced by my G-Suite administrator!
I think that it could be the problem.
I'm on Windows and tried several things in this days.
1) Used a portable version of Chromium on the same PC of my "regular" Chrome installation
2) tried on a different computer where I never worked on
Always the same problem.
So this must be something related to the synchronization of my G-Suite account.
I don't know what to do...

**Comment by al-caughey** [comment]
I had an a-ha moment a couple of days ago... it is a naming conflict in the CSS... at least a couple of extensions have also chosen to apply a style named `btn` to their buttons and their CSS is clobbering mine.  I have changed the names of my styles to prevent this

**Comment by al-caughey** [comment]
Marking as closed
