### ISSUE TITLE
Multiple Entries

### ISSUE THREAD

**Issue by Dkneyse** [al-caughey/Google-Meet-Attendance#13]
First, thanks for creating something like this! It is very much appreciated as it is a requirement for us to take attendance for all of our face to face meets!

Second, is it possible to record all the times students enter and exit the Meet? I have some who enter and then leave during the lesson early, or get kicked and then re-enter.

**Comment by AlCaughey** [comment]
Thanks for the feedback!  The latest version of the extension records the
just `arrival` time (i.e., when they first join the Meet).  I'm not certain
how easy it would be to detect re-join or departure.  I'll definitely put
it on the To-do list but integration with Sheets and (hopefully) classroom
are my highest priority.

Al

**Comment by Dkneyse** [comment]
Dear Al,

Thanks for your response. It would be great if it could convert straight to
a Google Sheet but in the meantime I am just uploading it into my Drive
from the CSV file and cleaning it up from there.

Regards,
Ms. Kneyse



Danelle Kneyse


*MS CoordinatorGrade 6 Mathematics / Science**Grade 7 Science*
Riffa Views International School
*A Not-for-profit School*
*p:* +973 1656-5000 <+973%201656%205000>
*w:* www.rvis.edu.bh
<https://www.facebook.com/rvisbah>   <https://twitter.com/rvis_bh>
<https://instagram.com/rvis.bh>

**Comment by AlCaughey** [comment]
Danelle - what sort of cleanup do you need to do?

Thx

**Comment by Dkneyse** [comment]
Dear Al,

Since today was only my second time using the extension, I am finding the
way that it names the students when they enter the meet. When I save the
names and timestamps there are all of the question marks next to the names
so I am having to delete those. I am making each of my classes a new tab,
and then I will just import the new data after each class.

So just reformatting it the way I like it I guess is what I meant by
"cleaning it up".

Regards,
Ms. Kneyse



Danelle Kneyse


*MS CoordinatorGrade 6 Mathematics / Science**Grade 7 Science*
Riffa Views International School
*A Not-for-profit School*
*p:* +973 1656-5000 <+973%201656%205000>
*w:* www.rvis.edu.bh
<https://www.facebook.com/rvisbah>   <https://twitter.com/rvis_bh>
<https://instagram.com/rvis.bh>

**Comment by al-caughey** [comment]
closed
