### ISSUE TITLE
Allow a "time joined" option

### ISSUE THREAD

**Issue by Suyashtnt** [al-caughey/Google-Meet-Attendance#15]
basically shows what time in the meeting  person joined, not sure if its posibble or not

**Comment by al-caughey** [comment]
I am capturing that information (i.e., the time that they arrive in the Meet).  I do not display it during the meet but it is saved to the CSV file... 

Actually, I just took a look at my CSV from today and it looks like not all of the student's entry times were captured... I will have to debug that?!?

**Comment by al-caughey** [comment]
marking as closed
