### ISSUE TITLE
Unable to Locate CSV File

### ISSUE THREAD

**Issue by mdstanberry** [al-caughey/Google-Meet-Attendance#16]
I'm unable to locate the saved CSV file.  I have a Meet Recordings folder on Google My Drive, but nothing is being save there.  FYI... This is within the GSA government network.  They allowed the install of the Meet Attendance extension - but I don't believe they fully tested it.  Don't know if government security constraints may be causing some issues.

**Comment by al-caughey** [comment]
My extension - **Google Meet Attendance** - writes the attendance information into a CSV file (which gets saved to your downloads directory).

There is another extension named `**Meet Attendance**` which saves files things to Google Drive (https://chrome.google.com/webstore/detail/meet-attendance/nenibigflkdikhamlnekfppbganmojlg?authuser=0&hl=en).  You might want to see if that is the one you're using.

Sorry for the confusion... I was not aware of the other extension when I chose the name of mine (and it'll take a bunch of time to change the name of mine now)

**Comment by al-caughey** [comment]
Assuming that this comment is misdirected (as above), I'm closing the issue
