### ISSUE TITLE
Red text flashes on load?

### ISSUE THREAD

**Issue by Eagle-Man** [al-caughey/Google-Meet-Attendance#17]
In 0.5.0+, on loading the Meet page there is a quick flash of a larger box with red text.  I think this is the "empty list" text.  Is it possible to suppress this until the first list is loaded for a smoother experience?

**Comment by AlCaughey** [comment]
I think that would be easy to do... Thanks for the suggestion

**Comment by al-caughey** [comment]
I think I have that added now... likely out in v0.5.3 in the next couple of
days

**Comment by conchesness** [comment]
Might it be possible to add some additional text (like unique ID number) to
the student list when we paste it in? Would make it easier to merge it in
to our SIS or other spreadsheets.
