### ISSUE TITLE
Transparency deactivated

### ISSUE THREAD

**Issue by Eagle-Man** [al-caughey/Google-Meet-Attendance#18]
Hi Al,

Love the new changes in 0.5.4, however, it seems that you have deactivated the transparency of the attendance layer.  I really like the transparency as it allows me to have the list up, but not block my view of people.

**Comment by AlCaughey** [comment]
At my end, the transparency comes back if you hide the attendance field (by
clicking the green check at the bottom) and then click it again to show the
field.  I can change that though...

**Comment by al-caughey** [comment]
I've changed things for the next version... clicking the red x will close the class list and toolbar and you'll have to click the green check at the bottom to make it visible again (but now with opacity... 

Is that what you'd like to see?

**Comment by Eagle-Man** [comment]
Is it not possible to include the start text with opacity?  Or is it a different kind of layer?  Would it be possible to enable opacity automatically when the X is clicked?

If the choice is between the two, I think I'd rather have it show up with the start text immediately, even without opacity, since I always want the list present, never hidden.  The collapsed view is fairly unobtrusive, just not great (would be better if it stayed where I placed it ;) ), so that's not too hard to work with.
