### ISSUE TITLE
Remember previous location?

### ISSUE THREAD

**Issue by Eagle-Man** [al-caughey/Google-Meet-Attendance#19]
Would it be possible for the extension to remember where it was last placed?  I try to move it to where it's most out of the way for me, but then every so often it resets to a default position.

*note: if this is enabled, it might also be worth preventing the top from being moved outside the window, as it might get stuck out there.

**Comment by al-caughey** [comment]
I'll look into this
It'll be relatively simple to do I think... keeping it on the screen might be the harder bit

**Comment by al-caughey** [comment]
Will be available in the next release... closing
