### ISSUE TITLE
CSV issues

### ISSUE THREAD

**Issue by Eagle-Man** [al-caughey/Google-Meet-Attendance#22]
v0.6.1

Two issues with the csv export.

1) Edge case: if first student is absent, then there's a missing cell in the csv, resulting in the first line time being shifted left one cell.
![image](https://user-images.githubusercontent.com/53746675/83681946-0b373180-a598-11ea-9829-cf2e72c11797.png)

2) I've mentioned this in the Facebook group.  Some entries in the csv are getting an extra value which includes an extra time with typically (0) or (1) minute of Meet presence.  Often they are just after the user connects or just before the user disconnects, but sometimes are after they disconnect.
![image](https://user-images.githubusercontent.com/53746675/83682336-ae884680-a598-11ea-9cf3-cf66d18b6605.png)

![image](https://user-images.githubusercontent.com/53746675/83683290-01163280-a59a-11ea-88cc-5b978248fcd6.png)

![image](https://user-images.githubusercontent.com/53746675/83689330-b1d4ff80-a5a3-11ea-99db-3a13dfaf3b36.png)

![image](https://user-images.githubusercontent.com/53746675/83682523-decfe500-a598-11ea-9f01-74b94b83e5a7.png)

Here is the html file for the above attendance, in case that helps.
![image](https://user-images.githubusercontent.com/53746675/83683137-c4e2d200-a599-11ea-9829-939334c9f28a.png)

Every day there seem to be a few, but it doesn't seem to be related to dropped called or reconnecting, and I believe it's different people each time (though I haven't been keeping

**Comment by Eagle-Man** [comment]
Note: the last 3 are the same class, different days.

**Comment by al-caughey** [comment]
Is there a case difference in the names as they were entered and then
updated?

**Comment by Eagle-Man** [comment]
No.  All names are set for the students, and are first name, last initial, two caps only.  I haven't changed the names of the students in my list either.   Also, if that were the case, I would expect to see the same students having the extra data all the time, but it's different students (see the last 3, long lists, which are all the same class)

**Comment by al-caughey** [comment]
If a student joins a class and then leaves and rejoins, Google gives them a different participant ID which creates the additional entries in the CSV file
