### ISSUE TITLE
Unable to record attendance

### ISSUE THREAD

**Issue by tiqbal123** [al-caughey/Google-Meet-Attendance#24]
Hi
I am having an issue recording attendance. When I click on Meet attendance icon it says, 
"Google Meet attendance only runs in an active Meet"
I have tried uninstalling and re installing etc but somehow I keep getting this.
Am I doing something wrong here?

**Comment by Eagle-Man** [comment]
It seems like a silly question, but you didn't explicitly state it...were you in an active Meet at the time?

If you were in an active Meet, what did you see/not see?  If you open the JS console (ctrl+shift+J), do you see any lines coming from attendance.js (look at the right-hand side)?  What version of the extension do you have?

**Comment by al-caughey** [comment]
That text is in the popup menu... It serves no purpose (and has no impact whatsoever on the proper functioning of the extension) so to avoid this sort of confusion, I have removed it from my dev builds.

**Comment by al-caughey** [comment]
OTOH, if things are not working for you, please send screenshots or a short video.

**Comment by tiqbal123** [comment]
It looks like its sorted! Thanks
________________________________
