### ISSUE TITLE
Why the meeting attendance is not running (duration = 0)

### ISSUE THREAD

**Issue by GeWaga201** [al-caughey/Google-Meet-Attendance#25]
When I strat the meeting, it shous the time of the start but the duration is 0.
![meeting attendance](https://user-images.githubusercontent.com/67153506/85135347-539b5400-b214-11ea-8c1a-a240259a98a1.png)

**Comment by AlCaughey** [comment]
Does it stay 0 for your entire Meet? It should count up from zero
