### ISSUE TITLE
Effect of Internet on Class Attendance Duration

### ISSUE THREAD

**Issue by arulyan** [al-caughey/Google-Meet-Attendance#28]
While seeing the attendance report of students, even since all the students attended the class attentively, listened, and responded properly I am able to see lots of white/gray spaces and not just pieces but as a long row of white/gray spaces. I guess white/gray spaces mean that they were not present in the class at that time. But I know that those people were present since I interacted with them. Therefore I am not able to understand the white/gray color row. It will be kind if you can help me explain what that color is or if this is an issue kindly look into it.

**Comment by al-caughey** [comment]
If there are grey/white spaces between patches of green, it means that those students were not visible on you Meet screen at those times.  The most common cause of this is related to Grid View... either not working properly, not being enabled, the `show only participants with video` option being selected.

Make sure that you have a working copy of Grid View... currently that is Grid View (fix) https://chrome.google.com/webstore/detail/google-meet-grid-view-fix/dakebdbeofhmlnmjlmhjdmmjmfohiicn?hl=en&authuser=0
