### ISSUE TITLE
names being added twice if the class list is empty

### ISSUE THREAD

**Issue by al-caughey** [al-caughey/Google-Meet-Attendance#3]
I had not noticed this before so think I've added it recently...

to reproduce, join a meet when the class list is empty... names will get added two times right after each other.  Not sure why that is happening?!?

**Comment by Eagle-Man** [comment]
Even if the class list is not empty, it seems new names added automatically to the list occur twice.

**Comment by al-caughey** [comment]
I think that should be fixed now.  I'm not seeing here anymore

**Comment by AlCaughey** [comment]
Marking as closed

**Comment by al-caughey** [comment]
closed
