### ISSUE TITLE
The full name of student is sometimes not visible in the attendance report 

### ISSUE THREAD

**Issue by AbstractMathematics** [al-caughey/Google-Meet-Attendance#30]
The name of students in their google account is first name + the last name and roll-number joined together, though even after this for some students the attendance report only generates the first name, not the last name, as shown in the pic below, 
![Annotation 2020-08-11 171717](https://user-images.githubusercontent.com/69510505/89893756-91a26c00-dbf6-11ea-975b-0e6afa3d0bcb.png)

and in attendance sheet i got,
![w2](https://user-images.githubusercontent.com/69510505/89894157-42a90680-dbf7-11ea-8480-3b2f15865a14.png)

**Comment by al-caughey** [comment]
I suspect this is something to do with you GSuite Admin settings (you'll have to talk to your IT folks about this) or perhaps the student is connecting to the Meet with their personal email rather than school assigned or via a private browsing window.

There's not much I can do about this...
