### ISSUE TITLE
Google Meet unresponsive when Attendance extension is loaded

### ISSUE THREAD

**Issue by adithyak04** [al-caughey/Google-Meet-Attendance#31]
My laptop is completely stuck and I am not even able to view members of the meet. I am only getting a confirm box which asks me to either wait or to exit. Google Meet works fine when this extension is not enabled. I have used the extension till yesterday, which worked smoothly, but now it is not. I previously had Google Meet Grid View, but I uninstalled that also.  But still not working

**Comment by AlCaughey** [comment]
Yes there was a bug... I've posted an update to the Chrome web store and it
should automatically be updated in your browser shortly

I'm terribly sorry for the inconvenience

**Comment by adithyak04** [comment]
Thanks for resolving it at the earliest

**Comment by al-caughey** [comment]
closed as per comments above
