### ISSUE TITLE
attendance window "stuck" on my mouse

### ISSUE THREAD

**Issue by sdillon92123** [al-caughey/Google-Meet-Attendance#45]
had a google meet open. about 15min into meet, the mouse was "stuck" on the attendance window. I could not do anything in the meet except scroll with my mouse ball. when i moved the cursor off the meet page i could close out the window or work on other windows.

**Comment by AlCaughey** [comment]
This occurs when the extension is updated in the background... I am able to
reproduce it (easily) but do not have a solution yet.  It will likely only
occur if Google updates the extension while you are in a Meet

Reload the page (<ctrl>+F5) to fix the issue

**Comment by al-caughey** [comment]
closing as a known issue and to a certain extent, beyond my control (i.e., Google updating an extension while it is running.)

I am *still* looking for a solution to this though
