### ISSUE TITLE
Multi Classes Bug

### ISSUE THREAD

**Issue by JustinVR** [al-caughey/Google-Meet-Attendance#46]
My wife is a Music teacher who sees 13 classes a day. She doesn't close out her chrome window so when each class is saved the names of the previous classes are automatically added to the next classes list. I believe it is because the localstorage variable just keeps adding to the list. She does have a new Google meets link for each class.

**Comment by AlCaughey** [comment]
She can 'Add' classes in the drop down menu in the top left corner of the
attendance dialog

**Comment by JustinVR** [comment]
Oh wonderful. Thank you for your quick reply!

**Comment by AlCaughey** [comment]
Before each class,she simply chooses one of her named classes
