### ISSUE TITLE
Continuing development

### ISSUE THREAD

**Issue by kevinnls** [al-caughey/Google-Meet-Attendance#63]
hi @al-caughey 
i landed up here from the thread on Google Support. your last post on the thread said you are saddened that the extension would be replaced by an in-built feature. i just wanted to point out that your extension is still required until the new feature does roll out, and that the feature appears to be only for Enterprise Education; so this is still an extension required by the institutions using non-enterprise education plans!
so cheers!
PS: i would like to contribute some time. haven't read the code yet. but is there a guideline/preferred procedure for contributions to this project?

**Comment by al-caughey** [comment]
I'd love to get a second set of eyes on the code!

I'm in the throes of a big revamp which makes it even more important 

I'll post the changes asap
