### ISSUE TITLE
"Leave page?" notification when leaving Meets

### ISSUE THREAD

**Issue by Eagle-Man** [al-caughey/Google-Meet-Attendance#9]
I don't think this was happening yesterday, but today, every time I leave a meet, I get a "leave page?" notification warning that "unsaved data will be lost."

**Comment by al-caughey** [comment]
I've added a `beforeunload` unload listener that complains if there are unsaved changes in the field (i.e., the [txt] button is visible)... 

I think I might be overzealously showing it on line 427... I don't recall why I added that line.  Try commenting it out

**Comment by al-caughey** [comment]
I have removed the line 427 above...
